
const Constants = {
  NUMBER_OF_PAYCHECKS_IN_YEAR: 26,
  PAYMENT_PER_PAYCHECKS: 2000,
  EMPL_COST_BENEFIT_PER_YEAR: 1000,
  DEPENDENT_COST_PER_YEAR: 500,
  DISCOUNT_EMPL_DEP : 0.1,
  NAME_START_WITH_A: 'A',
  ADD_DEPENDENT: "ADD_DEPENDENT",
  DELETE_DEPENDENTS: "DELETE_DEPENDENTS",
  ADD_INCOME: "ADD_INCOME"

  
}
export default Constants